
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 12 13:02:02 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 28;
  public static final int LTE = 24;
  public static final int LBRACKET = 33;
  public static final int CONST = 14;
  public static final int SEMI = 38;
  public static final int LPAREN = 31;
  public static final int CONTINUE = 11;
  public static final int MINUS = 16;
  public static final int CHARACTER = 44;
  public static final int RPAREN = 32;
  public static final int AND = 26;
  public static final int LT = 25;
  public static final int OR = 27;
  public static final int BOOL = 42;
  public static final int COMMA = 40;
  public static final int DIV = 18;
  public static final int PLUS = 15;
  public static final int IF = 4;
  public static final int DOT = 30;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 29;
  public static final int RETURN = 9;
  public static final int EQUAL = 39;
  public static final int RBRACKET = 34;
  public static final int NEW = 6;
  public static final int error = 1;
  public static final int MUL = 17;
  public static final int PERCENT = 19;
  public static final int NUMBER = 43;
  public static final int NEQ = 21;
  public static final int IDENT = 41;
  public static final int BREAK = 2;
  public static final int VOID = 10;
  public static final int EQ = 20;
  public static final int GTE = 23;
  public static final int ARROW = 35;
  public static final int FOREACH = 12;
  public static final int LBRACE = 36;
  public static final int ELSE = 3;
  public static final int READ = 8;
  public static final int WHILE = 5;
  public static final int RBRACE = 37;
  public static final int PROG = 13;
  public static final int GT = 22;
  public static final int PRINT = 7;
}

